development:
  adapter: postgresql
  database: graceful_hoppers_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: graceful_hoppers_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: graceful_hoppers_production
  user: 'ubuntu'
  pool: 5
  timeout: 5000
